"""empty message

Revision ID: 05eb56b87977
Revises: d16a69b362e4
Create Date: 2024-04-24 10:49:30.369155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05eb56b87977'
down_revision = 'd16a69b362e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('planets', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user'], ['id'])
        batch_op.create_foreign_key(None, 'planets', ['planets'], ['id'])
        batch_op.drop_column('rotation_period')
        batch_op.drop_column('name')
        batch_op.drop_column('diameter')
        batch_op.drop_column('orbital_period')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orbital_period', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('diameter', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('rotation_period', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('planets')
        batch_op.drop_column('user')

    # ### end Alembic commands ###
