"""empty message

Revision ID: 2f79ad98e163
Revises: c5bbfa8e9969
Create Date: 2024-04-26 11:04:57.368341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f79ad98e163'
down_revision = 'c5bbfa8e9969'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planets', sa.Integer(), nullable=True))
        batch_op.drop_constraint('favorite_planets_planets_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'planets', ['planets'], ['id'])
        batch_op.drop_column('planets_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planets_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorite_planets_planets_id_fkey', 'planets', ['planets_id'], ['id'])
        batch_op.drop_column('planets')

    # ### end Alembic commands ###
