"""empty message

Revision ID: 5520462449ca
Revises: 0cb2abd57fc2
Create Date: 2024-04-29 09:00:46.821672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5520462449ca'
down_revision = '0cb2abd57fc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('characters_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('favorite_characters_user_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorite_characters_characters_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'characters', ['characters_id'], ['id'])
        batch_op.drop_column('user')
        batch_op.drop_column('characters')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('characters', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorite_characters_characters_fkey', 'characters', ['characters'], ['id'])
        batch_op.create_foreign_key('favorite_characters_user_fkey', 'user', ['user'], ['id'])
        batch_op.drop_column('characters_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
