"""empty message

Revision ID: 6c7e834305bf
Revises: b0594bcae0c8
Create Date: 2024-04-24 11:44:49.437610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c7e834305bf'
down_revision = 'b0594bcae0c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('characters', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('planets', sa.Integer(), nullable=True))
        batch_op.drop_constraint('favorite_user_email_key', type_='unique')
        batch_op.create_foreign_key(None, 'planets', ['planets'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user'], ['id'])
        batch_op.create_foreign_key(None, 'characters', ['characters'], ['id'])
        batch_op.drop_column('email')
        batch_op.drop_column('password')
        batch_op.drop_column('name')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('favorite_user_email_key', ['email'])
        batch_op.drop_column('planets')
        batch_op.drop_column('characters')
        batch_op.drop_column('user')

    # ### end Alembic commands ###
