"""empty message

Revision ID: bcafb3bc2791
Revises: 6c7e834305bf
Create Date: 2024-04-24 14:36:40.120377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcafb3bc2791'
down_revision = '6c7e834305bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('characters', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('planets', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['characters'], ['characters.id'], name='favorite_user_characters_fkey'),
    sa.ForeignKeyConstraint(['planets'], ['planets.id'], name='favorite_user_planets_fkey'),
    sa.ForeignKeyConstraint(['user'], ['user.id'], name='favorite_user_user_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorite_user_pkey')
    )
    # ### end Alembic commands ###
