"""empty message

Revision ID: c5bbfa8e9969
Revises: bcafb3bc2791
Create Date: 2024-04-26 10:58:50.188823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5bbfa8e9969'
down_revision = 'bcafb3bc2791'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('planets_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('favorite_planets_planets_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorite_planets_user_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'planets', ['planets_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('planets')
        batch_op.drop_column('user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('planets', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorite_planets_user_fkey', 'user', ['user'], ['id'])
        batch_op.create_foreign_key('favorite_planets_planets_fkey', 'planets', ['planets'], ['id'])
        batch_op.drop_column('planets_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
